@startuml
|Secretary|
start
:Register student;
:Record intake;
:Add guardians;
:Enroll in program;

|School Coordinator / Program Coordinator|
  repeat
  :Track academics & attendance;
  if (Drop or Complete?) then (Yes)
    :Request status change;
  else (No)
    if (Transition needed?) then (Yes)
      :Request program change;
    else (No)
      stop
    endif
  endif

  |Director|
  :Review request;
  if (Approved?) then (Yes)
    stop
  else (No)
    :Add rejection note;
  endif
|School Coordinator / Program Coordinator|
repeat while (Review notes)
@enduml